"""init db

Revision ID: e42736d9775a
Revises: 
Create Date: 2025-08-26 16:33:36.852203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42736d9775a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lalafo_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('last_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lalafo_id')
    )
    op.create_index(op.f('ix_ads_id'), 'ads', ['id'], unique=False)
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('last_page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_id'), 'filters', ['id'], unique=False)
    op.create_index(op.f('ix_filters_user_id'), 'filters', ['user_id'], unique=False)
    op.create_table('filter_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=True),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('seen_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filter_id', 'ad_id', name='uq_filter_ad')
    )
    op.create_index(op.f('ix_filter_ads_id'), 'filter_ads', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filter_ads_id'), table_name='filter_ads')
    op.drop_table('filter_ads')
    op.drop_index(op.f('ix_filters_user_id'), table_name='filters')
    op.drop_index(op.f('ix_filters_id'), table_name='filters')
    op.drop_table('filters')
    op.drop_index(op.f('ix_ads_id'), table_name='ads')
    op.drop_table('ads')
    # ### end Alembic commands ###
