services:
  db:
    image: postgres:15
    container_name: lala_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-lalafo_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-barbariS2005*}
      POSTGRES_DB: ${POSTGRES_DB:-lalafo_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    container_name: lala_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: lala_app
    command: python bot.py
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    container_name: lala_worker
    command: celery -A utils.celery_app worker -l info --pool=solo
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  beat:
    build: .
    container_name: lala_beat
    command: celery -A utils.celery_app beat -l info
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  db_data:

